### ISSUE TITLE
Checklist!

### ISSUE THREAD

**Issue by JonSno29** [jgporter24/Trippie#1]
* PROJECT # 2.

As you enter the last phase of the boot camp, you’ll begin to apply for development jobs. If you want to land interviews, your portfolio must feature high-quality deployed examples of your work—and you can use your finished projects for that very purpose.

- [] Use Node.js and express to create RESTful API.
- [] Deploys to Heroku.
- [] Responsive to user input.
- [] Use Handlebars.js as  the templating engine.
- [] Use MySQL and the Sequelize ORM for the database.
- [] Use at least one new library, package or technology that we have not discussed.
- [] Good file structure that meets MVC paradigm.
- [] Include authentication (express-session and cookies)
- [] Protect API keys and sensitive information with environmental variables. (.env)
- [] Have GET and POST routes for adding and retrieving new data.
- [] Responsive.
- [] Be very descriptive on "COMMITS".
- [] Add Project #2 to your portfolio.
- [] Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id naming conventions, indentation, quality comments, etc.).
- [] Have a quality README (with unique name, description, technologies used, screenshot, and link to deployed application).

**__PRESENTATION__**
      -10 minutes-
- [] Elevator pitch(One minute).
- [] Concept: User story.
- [] Process: Technologies used, How tasks and roles were broken down, Our challenges and successes.
- [] Demo our project, slide deck.
- Directions for future development.
- Links to deployed application and the github repository. 

 **__**The Project Process              PowerPoint**__**

- [] Technologies used.
- [] How were tasks delegated.
- [] Challenge's.
- [] Our Successes.
- [] Demo the project.
- [] Directions for future development.
- [] GitHub repository link.
- [] Live Website link.
- [] Why this project idea is unique and novel.

**__EACH MEMBER INDIVIDUALLY__**

- [] Deployed URL or Project #2.
- [] URL of Project #2 GitHub repository. 
- [] URL of YOUR portfolio with Project#2 added to it.

- [] Dress nice...If you want. 
Pants are optional.
